# eidos_agent/features/firmament/npcs/npc_improviser.py
import logging
from typing import Optional, Dict, Any, List
import httpx
import json
import asyncio
import re

try:
    from ....core.config import LLMConfig, Config
    from ....llm_integrations.llm_client import LLMClient
    from ....core.http_client_manager import HTTPClientManager # New import
except ImportError: # pragma: no cover
    print("NPCImproviser: Could not import core components (Config, LLMClient, HTTPClientManager). Using dummy types.")
    LLMConfig = Dict[str, Any]; #type:ignore
    class Config: #type:ignore
        @staticmethod
        def get_firmament_module_config(): return {"firmament_llm_role": "FIRMAMENT_PRIMARY_DUMMY"}
        @staticmethod
        def get_llm_config(role_name):
            return {"role": role_name, "model":"d_model", "url":"http://d_url", "timeout":10.0} if role_name == "FIRMAMENT_PRIMARY_DUMMY" else None

    class LLMClient: #type:ignore
        """Dummy LLMClient for use when actual import fails."""
        def __init__(self, http_client: Any):
            self.http_client = http_client
            # print(f"Dummy LLMClient initialized with http_client: {http_client}")
        async def call_llm_api(self, llm_config: LLMConfig, messages: List[Dict[str, str]], stream: bool = False, **kwargs):
            # print(f"DUMMY LLMClient.call_llm_api called. Role: {llm_config.get('role')}, Stream: {stream}")
            name_from_prompt = "Unknown NPC"
            if messages and isinstance(messages, list) and len(messages) > 0:
                user_prompt = messages[-1].get("content", "")
                hint_match = re.search(r"Name Hint: (\w+)", user_prompt)
                if hint_match: name_from_prompt = hint_match.group(1)

            mock_json_response = json.dumps({
                "id": f"{name_from_prompt.lower().replace(' ','_')}_dummy_id_{random.randint(100,999)}",
                "name": f"{name_from_prompt} (Dummy LLM Shared Client)",
                "appearance": "Generated by dummy LLMClient via shared HTTP manager",
                "role": "Placeholder Role from Dummy Client",
                "personality": "Simulated and Agreeable",
                "relationship_to_pathos": "Test subject for shared client architecture",
                "initial_dialogue": f"I am {name_from_prompt}, a figment from a dummy LLM using a shared client."
            })
            yield mock_json_response
            if False: yield # Makes it an async generator

    from unittest.mock import MagicMock # For dummy HTTPClientManager if httpx not available
    class HTTPClientManager: # New Dummy #type:ignore
        _instance = None
        @classmethod
        def instance(cls):
            if not cls._instance:
                # print("Dummy HTTPClientManager: Creating new instance.")
                cls._instance = cls()
            return cls._instance
        def get_client(self):
            # print("Dummy HTTPClientManager: get_client() called, returning MagicMock.")
            # Ensure the mock client has an `aclose` if real httpx.AsyncClient is not available for spec
            mock_client = MagicMock() # spec=httpx.AsyncClient if httpx imported, else just MagicMock
            if hasattr(httpx, 'AsyncClient'): mock_client = MagicMock(spec=httpx.AsyncClient)
            mock_client.is_closed = False # Simulate an open client
            return mock_client
        async def shutdown(self): pass

logger = logging.getLogger(__name__)
# Ensure random is imported if the dummy LLMClient uses it.
if 'random' not in globals(): import random # type: ignore

class NPCImproviser:
    def __init__(self, firmament_llm_role_name: Optional[str] = None):
        if firmament_llm_role_name:
            self.llm_role_name = firmament_llm_role_name
        else:
            fm_module_cfg = Config.get_firmament_module_config() if callable(getattr(Config, 'get_firmament_module_config', None)) else {}
            self.llm_role_name = fm_module_cfg.get("firmament_llm_role", "FIRMAMENT_PRIMARY")

        self.llm_config: Optional[LLMConfig] = Config.get_llm_config(self.llm_role_name) if callable(getattr(Config, 'get_llm_config', None)) else None

        if not self.llm_config: # pragma: no cover
            logger.error(f"NPCImproviser: LLM config for role '{self.llm_role_name}' not found. Improvisation might fail or use fallbacks.")
        else:
            logger.info(f"NPCImproviser initialized for LLM role '{self.llm_role_name}'. Model: '{self.llm_config.get('model', 'N/A')}'")

        # Get shared HTTPClientManager instance
        self.http_client_manager = HTTPClientManager.instance() # This gets the singleton
        if not (hasattr(self.http_client_manager, 'get_client') and callable(self.http_client_manager.get_client)) or \
           ("dummy" in str(type(self.http_client_manager)).lower()): # Basic check for dummy
             logger.warning("NPCImproviser: Using a DUMMY HTTPClientManager or it's invalid. Real LLM calls will fail.") # pragma: no cover
        else:
             logger.info("NPCImproviser: Shared HTTPClientManager instance obtained.")


    def _build_improvisation_prompt(self, name_hint, subconscious_thought_context, scene_context) -> str:
        # (Full _build_improvisation_prompt logic from previous step is assumed here)
        location_description = scene_context.get("location_description", "an unspecified place")
        pathos_mood_state = scene_context.get("pathos_mood_state", "neutral")
        current_activity = scene_context.get("current_activity_name", "not currently specified")
        time_of_day = scene_context.get("time_of_day", "not specified")
        recent_world_events_summary = scene_context.get("recent_world_events_summary", "nothing notable recently.")
        pathos_current_intention = scene_context.get("pathos_current_intention", None)
        prompt_lines = [
            "Based on the following context, generate a detailed NPC profile.", "---",
            "**Current Scene for Pathos:**", f"- Location: {location_description}", f"- Time: {time_of_day}",
            f"- Pathos's Current Activity: {current_activity}", f"- Pathos's Current Mood: {pathos_mood_state}"
        ]
        if pathos_current_intention: prompt_lines.append(f"- Pathos's Current Intention/Goal: {pathos_current_intention}")
        prompt_lines.append(f"- Recent World Events Summary: {recent_world_events_summary}"); prompt_lines.append("---")
        if name_hint:
            prompt_lines.append(f"**NPC to Improvise (Name Hint: {name_hint}):**")
            prompt_lines.append(f"Pathos is thinking about or might encounter someone named or similar to '{name_hint}'.")
        else:
            prompt_lines.append("**NPC to Improvise (No Name Hint):**")
            prompt_lines.append("Pathos might encounter a new character relevant to the scene or role.")
        if subconscious_thought_context:
            prompt_lines.append(f"Pathos's recent subconscious thought: \"{subconscious_thought_context}\"")
            prompt_lines.append("Consider emotional tone or implied relationship from this thought.")
        prompt_lines.append("---"); prompt_lines.append("**Required JSON Output Fields:** id, name, appearance, role, personality, relationship_to_pathos, initial_dialogue.")
        prompt_lines.append("Ensure 'id' is unique, lowercase, snake_case. 'initial_dialogue' is a single characteristic line.")
        return "\n".join(prompt_lines)


    async def improvise_npc(
        self, name_hint: Optional[str] = None,
        subconscious_thought_context: Optional[str] = None,
        scene_context: Optional[Dict[str, Any]] = None
    ) -> Optional[Dict[str, Any]]:
        if scene_context is None: scene_context = {}
        if not self.llm_config or not self.llm_config.get("url"):
            logger.error(f"NPCImproviser: LLM URL for role '{self.llm_role_name}' is missing or config not loaded. Cannot improvise.")
            return None

        # Get shared httpx.AsyncClient from the manager
        if not self.http_client_manager: # Should have been set in __init__
             logger.error("NPCImproviser: HTTPClientManager was not initialized. Cannot make LLM call.") # pragma: no cover
             return None

        shared_httpx_client = self.http_client_manager.get_client()
        if not shared_httpx_client: # Check if get_client() failed (e.g., manager's internal client init failed)
            logger.error(f"NPCImproviser: Could not obtain shared HTTP client from manager for role '{self.llm_role_name}'. LLM call aborted.")
            return None

        user_prompt_str = self._build_improvisation_prompt(name_hint, subconscious_thought_context, scene_context)
        system_message = "You are an expert character creator for a life simulation. Your task is to generate a plausible and contextually relevant NPC. Return ONLY a valid JSON object with the specified fields: id, name, appearance, role, personality, relationship_to_pathos, initial_dialogue."
        messages = [{"role": "system", "content": system_message}, {"role": "user", "content": user_prompt_str}]

        logger.info(f"NPCImproviser: Initiating LLM call (via shared HTTP client) for NPC improvisation. Role: '{self.llm_role_name}'.")
        # logger.debug(f"NPCImproviser User Prompt for LLM:\n{user_prompt_str}") # Can be very verbose

        full_response_content = ""
        llm_error: Optional[Any] = None # Can be string or dict from error_chunk
        parsed_npc_profile: Optional[Dict[str, Any]] = None

        try:
            # LLMClient is instantiated with the shared client provided by HTTPClientManager
            llm_api_client = LLMClient(http_client=shared_httpx_client)

            response_generator = llm_api_client.call_llm_api(
                llm_config=self.llm_config, messages=messages, stream=False
            )
            async for chunk in response_generator:
                if isinstance(chunk, str): full_response_content += chunk
                elif isinstance(chunk, dict) and chunk.get("type") == "error_chunk":
                    llm_error = chunk.get("payload", "Unknown LLM error from client's error_chunk")
                    break

            if llm_error:
                logger.error(f"NPCImproviser: LLM API client returned an error: {llm_error}")
                return None
            if not full_response_content:
                logger.warning("NPCImproviser: LLM returned empty content string.")
                return None

            # logger.debug(f"NPCImproviser: Raw LLM response string (len: {len(full_response_content)}): {full_response_content[:500]}...")

            json_match = re.search(r'{\s*".*?"\s*:.*?}', full_response_content, re.DOTALL)
            if not json_match:
                logger.error(f"NPCImproviser: No valid JSON object found in LLM response. Snippet: {full_response_content[:300]}")
                return None

            json_str = json_match.group(0)
            parsed_npc_profile = json.loads(json_str)

            if not isinstance(parsed_npc_profile, dict):
                logger.error(f"NPCImproviser: Parsed LLM response is not a dictionary. Type: {type(parsed_npc_profile)}")
                return None

            required_keys = ["id", "name", "appearance", "role", "personality", "relationship_to_pathos", "initial_dialogue"]
            for key in required_keys:
                val = parsed_npc_profile.get(key)
                is_missing_or_empty_str = not isinstance(val, str) or not val.strip()
                if key in ["id", "name"] and is_missing_or_empty_str: # ID and Name must be non-empty strings
                    logger.warning(f"NPCImproviser: LLM response missing or invalid essential key '{key}'. Profile: {parsed_npc_profile}")
                    if key == "name" and name_hint: parsed_npc_profile["name"] = name_hint
                    elif key == "id" and name_hint: parsed_npc_profile["id"] = name_hint.strip().lower().replace(" ","_") + "_improv_fb"
                    else: return None
                elif is_missing_or_empty_str and key not in ["id", "name"]: # Other fields can be empty strings if LLM chooses, but must exist
                     logger.debug(f"NPCImproviser: LLM response has empty or non-string value for optional key '{key}'. Using default or empty.")
                     parsed_npc_profile[key] = "" # Ensure key exists, even if empty, if LLM didn't provide string

            logger.info(f"NPCImproviser: Successfully improvised and validated NPC '{parsed_npc_profile.get('name')}'.")
            return parsed_npc_profile

        except httpx.HTTPError as e: # Catches ConnectError, TimeoutException, etc. # pragma: no cover
            logger.error(f"NPCImproviser: HTTP-related error during LLM call for role '{self.llm_role_name}': {e}", exc_info=False)
        except json.JSONDecodeError as e: # pragma: no cover
            logger.error(f"NPCImproviser: Failed to parse JSON from LLM response. Error: {e}. Response snippet: {full_response_content[:500]}")
        except Exception as e: # pragma: no cover
            logger.error(f"NPCImproviser: Unexpected error during NPC improvisation (using shared client): {e}", exc_info=True)

        return None
        # Note: The shared_httpx_client obtained from HTTPClientManager is NOT closed here.
        # Its lifecycle (open/close) is managed by the HTTPClientManager itself (e.g. on app shutdown).

if __name__ == '__main__': # pragma: no cover
    # Ensure random is imported if the dummy LLMClient uses it.
    import random
    logging.basicConfig(level=logging.DEBUG)

    async def main_test_improviser_shared_client():
        # Check if using dummy LLMClient or HTTPClientManager to set expectations
        is_dummy_llm_client = not hasattr(LLMClient, 'call_llm_api') or "dummy" in LLMClient.call_llm_api.__qualname__.lower()
        is_dummy_http_manager = "dummy" in str(type(HTTPClientManager.instance())).lower()

        if is_dummy_llm_client:
             print("\n----- WARNING: Using DUMMY LLMCLIENT for NPCImproviser __main__ test. -----\n")
        if is_dummy_http_manager:
             print("\n----- WARNING: Using DUMMY HTTPClientManager for NPCImproviser __main__ test. -----\n")

        improviser_instance = NPCImproviser() # Uses default FIRMAMENT_PRIMARY role from Config

        if not improviser_instance.llm_config or \
           not improviser_instance.llm_config.get("url") or \
           "dummy_llm_url" in improviser_instance.llm_config.get("url",""):
            print("NPCImproviser __main__ test: LLM config not properly loaded or points to a dummy URL.")
            print("Ensure .env is set up for the FIRMAMENT_PRIMARY role if you want to test with a real LLM.")
            if is_dummy_llm_client:
                print("The DUMMY LLMClient will be used, returning a fixed JSON structure.")
            else:
                print("Attempting to proceed, but real LLM calls might fail if endpoint isn't configured/available.")

        scene_context_example = {
            "location_description": "a dimly lit jazz club, smoke lingering in the air",
            "pathos_mood_state": "introspective and slightly melancholic",
            "current_activity_name": "nursing a drink at the bar",
            "time_of_day": datetime.now(timezone.utc).isoformat(),
            "recent_world_events_summary": "Heard news of an old acquaintance passing away earlier.",
            "pathos_current_intention": "Listen to the music and reflect."
        }

        print("\n--- Test Case 1: Improvising NPC 'Saxophonist Silas' ---")
        profile1 = await improviser_instance.improvise_npc(
            name_hint="Saxophonist Silas",
            subconscious_thought_context="The saxophone player tonight is incredible. Reminds me of someone...",
            scene_context=scene_context_example
        )
        if profile1: print(f"Generated Profile 1: {json.dumps(profile1, indent=2)}")
        else: print("Profile 1 generation FAILED.")

        print("\n--- Test Case 2: Improvising NPC 'Lara' (specific context in prompt) ---")
        profile_lara_shared = await improviser_instance.improvise_npc(
            name_hint="Lara",
            subconscious_thought_context="Is that Lara by the bar? What are the odds?",
            scene_context={"location_description": "the same jazz club", "pathos_mood_state":"surprised and curious"}
        )
        if profile_lara_shared: print(f"Generated Profile Lara (shared client): {json.dumps(profile_lara_shared, indent=2)}")
        else: print("Profile Lara (shared client) generation FAILED.")

        # Test for missing LLM URL (if config was manipulated or dummy used)
        print("\n--- Test Case 3: Improvising NPC with no LLM URL configured (simulated error) ---")
        original_url_for_test = None
        if improviser_instance.llm_config:
            original_url_for_test = improviser_instance.llm_config.get('url')
            improviser_instance.llm_config['url'] = "" # Simulate missing URL

        profile_no_url_shared = await improviser_instance.improvise_npc(name_hint="NoUrlNPCShared", scene_context=scene_context_example)
        assert profile_no_url_shared is None, "Should return None if URL is missing for shared client."
        print(f"Profile generation with no URL (shared client): {'Failed as expected' if profile_no_url_shared is None else 'Unexpectedly succeeded'}")

        # Restore URL if it was changed, for potential further tests or proper shutdown of manager
        if improviser_instance.llm_config and original_url_for_test is not None:
             improviser_instance.llm_config['url'] = original_url_for_test

        # Test HTTPClientManager shutdown (optional, as it's a shared manager)
        # If HTTPClientManager was imported correctly and is not a dummy
        if 'HTTPClientManager' in globals() and hasattr(HTTPClientManager, 'instance') and not ("dummy" in str(type(HTTPClientManager.instance())).lower()):
            print("\nAttempting to shutdown shared HTTPClientManager...")
            shared_manager_instance = HTTPClientManager.instance()
            if hasattr(shared_manager_instance, 'shutdown') and asyncio.iscoroutinefunction(shared_manager_instance.shutdown):
                 await shared_manager_instance.shutdown()
                 print("Shared HTTPClientManager shutdown called.")


    if hasattr(asyncio, 'run'):
        asyncio.run(main_test_improviser_shared_client())
    else: # Fallback for older Python if needed (e.g. some test environments) # pragma: no cover
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main_test_improviser_shared_client())

    print("\nNPCImproviser __main__ (with shared client structure) tests completed.")
