# eidos_agent/features/firmament/npcs/npc_improviser.py
import logging
from typing import Optional, Dict, Any, List
import httpx # Added
import json # Added
import asyncio # Added for __main__
import re # Added for JSON extraction

try:
    from ....core.config import LLMConfig, Config
    from ....llm_integrations.llm_client import LLMClient
except ImportError: # pragma: no cover
    print("NPCImproviser: Could not import LLMConfig/Config/LLMClient from ....core.config or ....llm_integrations. Using dummy types.")
    LLMConfig = Dict[str, Any]; #type:ignore
    class Config: #type:ignore
        @staticmethod
        def get_firmament_module_config(): return {"firmament_llm_role": "FIRMAMENT_PRIMARY_DUMMY"}
        @staticmethod
        def get_llm_config(role_name):
            if role_name == "FIRMAMENT_PRIMARY_DUMMY":
                return {"role": role_name, "model":"dummy_model_fallback", "url":"http://dummy_llm_url_for_npc_improviser", "timeout":10.0, "temperature": 0.7, "max_tokens": 512}
            return None
    class LLMClient: #type:ignore
        """Dummy LLMClient for use when actual import fails."""
        def __init__(self, http_client: Any):
            self.http_client = http_client
            # print(f"Dummy LLMClient initialized with http_client: {http_client}")

        async def call_llm_api(self, llm_config: LLMConfig, messages: List[Dict[str, str]], stream: bool = False, **kwargs):
            # print(f"DUMMY LLMClient.call_llm_api called. Role: {llm_config.get('role')}, Stream: {stream}")
            # Simulate a JSON response string for testing parsing
            name_from_prompt = "Unknown NPC"
            if messages and isinstance(messages, list) and len(messages) > 0:
                user_prompt = messages[-1].get("content", "")
                # Try to extract a name hint for more realistic dummy response
                hint_match = re.search(r"Name Hint: (\w+)", user_prompt)
                if hint_match:
                    name_from_prompt = hint_match.group(1)

            mock_json_response = json.dumps({
                "id": f"{name_from_prompt.lower().replace(' ','_')}_dummy_id_{random.randint(100,999)}",
                "name": f"{name_from_prompt} (Dummy LLM Generated)",
                "appearance": "Generated by dummy LLMClient with generic features",
                "role": "Placeholder Role from Dummy",
                "personality": "Simulated and agreeable",
                "relationship_to_pathos": "A test subject for the dummy LLM",
                "initial_dialogue": f"I am {name_from_prompt}, a figment of a dummy LLM's imagination."
            })
            # Simulate async generator behavior
            # For stream=False, it should yield the full content then stop.
            yield mock_json_response


logger = logging.getLogger(__name__)

class NPCImproviser:
    """
    Handles LLM-based generation of NPCs from scratch or from fuzzy thoughts/contexts.
    """
    def __init__(self, firmament_llm_role_name: Optional[str] = None):
        """
        Initializes the NPCImproviser.
        Args:
            firmament_llm_role_name (Optional[str]): The specific LLM role from Config.
        """
        if firmament_llm_role_name:
            self.llm_role_name = firmament_llm_role_name
        else:
            fm_module_cfg = Config.get_firmament_module_config() if callable(getattr(Config, 'get_firmament_module_config', None)) else {}
            self.llm_role_name = fm_module_cfg.get("firmament_llm_role", "FIRMAMENT_PRIMARY")

        self.llm_config: Optional[LLMConfig] = Config.get_llm_config(self.llm_role_name) if callable(getattr(Config, 'get_llm_config', None)) else None

        if not self.llm_config: # pragma: no cover
            logger.error(f"NPCImproviser: LLM configuration for role '{self.llm_role_name}' not found. Improvisation will be disabled or use fallbacks.")
        else:
            logger.info(f"NPCImproviser initialized to use LLM role '{self.llm_role_name}' with model '{self.llm_config.get('model', 'N/A')}'.")
        # Note: httpx.AsyncClient and LLMClient are now created per call in improvise_npc.

    def _build_improvisation_prompt(
        self,
        name_hint: Optional[str],
        subconscious_thought_context: Optional[str],
        scene_context: Dict[str, Any]
    ) -> str:
        """
        Constructs a detailed prompt for the LLM to generate an NPC profile.
        (This is the full version from the previous step, not the placeholder)
        """
        location_description = scene_context.get("location_description", "an unspecified place")
        pathos_mood_state = scene_context.get("pathos_mood_state", "neutral")
        current_activity = scene_context.get("current_activity_name", "not currently specified")
        time_of_day = scene_context.get("time_of_day", "not specified")
        recent_world_events_summary = scene_context.get("recent_world_events_summary", "nothing notable recently.")
        pathos_current_intention = scene_context.get("pathos_current_intention", None)

        prompt_lines = [
            # System message content is now part of the `messages` list in `improvise_npc`
            # This function will just return the user part of the prompt.
            "Based on the following context, generate a detailed NPC profile.",
            "---",
            "**Current Scene for Pathos:**",
            f"- Location: {location_description}",
            f"- Time: {time_of_day}",
            f"- Pathos's Current Activity: {current_activity}",
            f"- Pathos's Current Mood: {pathos_mood_state}"
        ]
        if pathos_current_intention:
            prompt_lines.append(f"- Pathos's Current Intention/Goal: {pathos_current_intention}")
        prompt_lines.append(f"- Recent World Events Summary: {recent_world_events_summary}")
        prompt_lines.append("---")

        if name_hint:
            prompt_lines.append(f"**NPC to Improvise (Name Hint: {name_hint}):**")
            prompt_lines.append(f"Pathos is thinking about or might encounter someone named or similar to '{name_hint}'.")
        else:
            prompt_lines.append("**NPC to Improvise (No Name Hint):**")
            prompt_lines.append("Pathos might encounter a new, unprompted character relevant to the scene, or a character might be needed to fulfill a role (e.g., shopkeeper at a shop location).")

        if subconscious_thought_context:
            prompt_lines.append(f"Pathos's recent subconscious thought related to this potential NPC: \"{subconscious_thought_context}\"")
            prompt_lines.append("Consider any emotional tone or implied relationship from this thought (e.g., nostalgia, curiosity, anxiety, a problem to solve).")

        prompt_lines.append("---")
        prompt_lines.append("**Required JSON Output Fields:** id, name, appearance, role, personality, relationship_to_pathos, initial_dialogue.")
        prompt_lines.append("Ensure the 'id' is a unique, lowercase, snake_case string. Base it on the name if possible.")
        prompt_lines.append("The 'initial_dialogue' should be a single, characteristic opening line.")

        return "\n".join(prompt_lines)


    async def improvise_npc(
        self,
        name_hint: Optional[str] = None,
        subconscious_thought_context: Optional[str] = None,
        scene_context: Optional[Dict[str, Any]] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Generates an NPC profile based on hints and context using an LLM.
        (Actual LLM call is now structured but may still use a dummy LLMClient if imports failed).
        """
        if scene_context is None:
            scene_context = {} # Default to empty context to avoid errors

        if not self.llm_config or not self.llm_config.get("url"): # Check for URL specifically
            logger.error(f"NPCImproviser: Cannot improvise NPC. LLM URL for role '{self.llm_role_name}' is missing or config not loaded.")
            return None

        user_prompt_str = self._build_improvisation_prompt(name_hint, subconscious_thought_context, scene_context)
        system_message = "You are an expert character creator for a life simulation. Your task is to generate a plausible and contextually relevant NPC. Return ONLY a valid JSON object with the specified fields: id, name, appearance, role, personality, relationship_to_pathos, initial_dialogue."

        messages = [
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_prompt_str}
        ]

        logger.info(f"NPCImproviser: Initiating LLM call for NPC improvisation. Role: '{self.llm_role_name}', Model: '{self.llm_config.get('model', 'N/A')}'")
        logger.debug(f"NPCImproviser: User part of prompt for LLM:\n------USER PROMPT START------\n{user_prompt_str}\n------USER PROMPT END------")
        logger.warning("TODO: NPCImproviser: httpx.AsyncClient is created per call. For performance, consider using a shared client instance managed by the application or a factory.")

        full_response_content = ""
        llm_error = None
        parsed_npc_profile: Optional[Dict[str, Any]] = None

        try:
            # Create httpx.AsyncClient per call for now.
            # Timeout should be part of LLMConfig, default if not present.
            timeout_duration = self.llm_config.get("timeout", 20.0) # Default to 20s if not in config
            async with httpx.AsyncClient(timeout=timeout_duration) as http_client:
                llm_api_client = LLMClient(http_client=http_client)

                response_generator = llm_api_client.call_llm_api(
                    llm_config=self.llm_config,
                    messages=messages,
                    stream=False # Expect a single JSON response, not streaming text
                )

                async for chunk in response_generator:
                    if isinstance(chunk, str):
                        full_response_content += chunk
                    elif isinstance(chunk, dict) and chunk.get("type") == "error_chunk": # Check for error chunk from LLMClient
                        llm_error = chunk.get("payload", "Unknown LLM error from client")
                        logger.error(f"NPCImproviser: LLMClient returned an error_chunk: {llm_error}")
                        break # Stop processing on error

                if llm_error:
                    return None

                if not full_response_content:
                    logger.warning("NPCImproviser: LLM returned empty content string.")
                    return None

                logger.debug(f"NPCImproviser: Raw LLM response string (len: {len(full_response_content)}): {full_response_content[:500]}...")

                # Attempt to parse the JSON response; LLMs sometimes add markdown or other text.
                # Regex to find the outermost JSON object.
                json_match = re.search(r'{\s*".*?"\s*:.*?}', full_response_content, re.DOTALL)
                if not json_match:
                    logger.error(f"NPCImproviser: No valid JSON object found in LLM response. Response snippet: {full_response_content[:300]}")
                    return None

                json_str = json_match.group(0)
                parsed_npc_profile = json.loads(json_str)

                if not isinstance(parsed_npc_profile, dict): # Should be a dictionary
                    logger.error(f"NPCImproviser: Parsed LLM response is not a dictionary. Got type: {type(parsed_npc_profile)}")
                    return None

                # Validate essential keys in the parsed dictionary
                required_keys = ["id", "name", "appearance", "role", "personality", "relationship_to_pathos", "initial_dialogue"]
                for key in required_keys:
                    if key not in parsed_npc_profile or \
                       not isinstance(parsed_npc_profile[key], str) or \
                       (key in ["id", "name"] and not parsed_npc_profile[key].strip()): # ID and Name must not be empty strings

                        logger.warning(f"NPCImproviser: LLM response missing or invalid essential key '{key}'. Profile: {parsed_npc_profile}")
                        # Attempt to salvage if name_hint is available and 'name' or 'id' is the issue
                        if key == "name" and name_hint and (not parsed_npc_profile.get("name") or not isinstance(parsed_npc_profile.get("name"), str)):
                            logger.info(f"Salvaging 'name' with name_hint: '{name_hint}'")
                            parsed_npc_profile["name"] = name_hint
                        elif key == "id" and name_hint and (not parsed_npc_profile.get("id") or not isinstance(parsed_npc_profile.get("id"), str)):
                            salvaged_id = name_hint.strip().lower().replace(" ", "_") + "_improv_fallback"
                            logger.info(f"Salvaging 'id' with name_hint, creating: '{salvaged_id}'")
                            parsed_npc_profile["id"] = salvaged_id
                        else: # If other crucial field is bad, or salvage failed
                            logger.error(f"NPCImproviser: Crucial field '{key}' remains invalid after salvage attempt. Discarding profile.")
                            return None

                logger.info(f"NPCImproviser: Successfully improvised and validated NPC '{parsed_npc_profile.get('name')}'.")
                return parsed_npc_profile

        except httpx.HTTPStatusError as e: # pragma: no cover
            logger.error(f"NPCImproviser: HTTP error during LLM call: Status {e.response.status_code} - Response: {e.response.text[:200]}", exc_info=False) # exc_info=False for brevity on HTTP errors unless debugging
        except httpx.RequestError as e: # pragma: no cover
            logger.error(f"NPCImproviser: Request error during LLM call (e.g., connection issue, timeout): {e}", exc_info=False)
        except json.JSONDecodeError as e: # pragma: no cover
            logger.error(f"NPCImproviser: Failed to parse JSON from LLM response. Error: {e}. Response snippet: {full_response_content[:500]}")
        except Exception as e: # pragma: no cover
            logger.error(f"NPCImproviser: Unexpected error during NPC improvisation: {e}", exc_info=True)

        return None


if __name__ == '__main__': # pragma: no cover
    # Ensure random is imported if the dummy LLMClient uses it.
    import random # For dummy LLMClient's name generation
    logging.basicConfig(level=logging.DEBUG) # DEBUG to see detailed prompt and response logs

    async def main_test():
        # Check if using dummy LLMClient
        if not hasattr(LLMClient, 'call_llm_api') or "dummy" in LLMClient.call_llm_api.__qualname__.lower():
             print("\n----- WARNING: Using DUMMY LLMCLIENT for __main__ test. Real LLM calls will NOT be made. -----\n")

        improviser = NPCImproviser()
        if not improviser.llm_config or not improviser.llm_config.get("url") or "dummy_llm_url" in improviser.llm_config.get("url",""):
            print("NPCImproviser __main__ test: LLM config not properly loaded or points to a dummy URL.")
            print("Ensure .env is set up for the FIRMAMENT_PRIMARY role if you want to test with a real LLM,")
            print("otherwise, the DUMMY LLMClient will provide a fixed JSON response.")
            print(f"Current improviser LLM role: {improviser.llm_role_name}, Config: {improviser.llm_config}")


        scene_context_example = {
            "location_description": "a quiet corner in a city library, afternoon",
            "pathos_mood_state": "thoughtful and slightly melancholic",
            "current_activity_name": "researching old city maps",
            "time_of_day": datetime.now(timezone.utc).isoformat(),
            "recent_world_events_summary": "A local festival was announced for next week.",
            "pathos_current_intention": "Find a clue about the missing historian."
        }

        print("\n--- Test Case 1: Improvising NPC 'Archivist Eleanor' ---")
        profile1 = await improviser.improvise_npc(
            name_hint="Archivist Eleanor",
            subconscious_thought_context="I need to find someone who knows about the old Westgate district. Maybe an archivist?",
            scene_context=scene_context_example
        )
        if profile1: print(f"Generated Profile 1: {json.dumps(profile1, indent=2)}")
        else: print("Profile 1 generation FAILED.")

        print("\n--- Test Case 2: Improvising NPC 'Lara' (specific context) ---")
        profile_lara = await improviser.improvise_npc(
            name_hint="Lara",
            subconscious_thought_context="That name sounds familiar... Lara from the climbing gym? She was fearless.",
            scene_context={"location_description": "a climbing gym reception area", "pathos_mood_state":"curious and reminiscent"}
        )
        if profile_lara: print(f"Generated Profile Lara: {json.dumps(profile_lara, indent=2)}")
        else: print("Profile Lara generation FAILED.")

        # Test for missing LLM URL (if config was manipulated or dummy used)
        print("\n--- Test Case 3: Improvising NPC with no LLM URL configured (simulated error) ---")
        original_url = None
        if improviser.llm_config:
            original_url = improviser.llm_config.get('url')
            improviser.llm_config['url'] = "" # Simulate missing URL

        profile_no_url = await improviser.improvise_npc(name_hint="NoUrl Npc", scene_context=scene_context_example)
        assert profile_no_url is None, "Should return None if URL is missing."
        print(f"Profile generation with no URL: {'Failed as expected' if profile_no_url is None else 'Unexpectedly succeeded'}")
        if improviser.llm_config and original_url is not None: # Restore
             improviser.llm_config['url'] = original_url


    if hasattr(asyncio, 'run'):
        asyncio.run(main_test())
    else: # Fallback for older Python if needed (e.g. some test environments)
        loop = asyncio.get_event_loop() # type: ignore
        loop.run_until_complete(main_test()) # type: ignore

    print("\nNPCImproviser __main__ async tests completed.")
