"""
Pydantic models for data exchange with the Pathos Subconscious Node API.

These models define the structure of data received from or sent to
the subconscious node, particularly for impulses and memory imprints.
"""
from pydantic import BaseModel
from typing import List, Dict, Any

class ImpulseData(BaseModel):
    """
    Represents an impulse detected by the Pathos Subconscious Node.

    An impulse is typically a thought that suggests an immediate desire
    or urge, influenced by the current mood state.
    """
    thought: str
    mood_snapshot: Dict[str, Any] # Captures the mood state at the time of the impulse
    timestamp: str # ISO 8601 format timestamp

class ImprintData(BaseModel):
    """
    Represents a memory imprint generated by the Pathos Subconscious Node.

    An imprint is a thought or realization considered significant enough
    to be stored in long-term (soft) memory.
    """
    content: str # The content of the thought/realization
    mood: Dict[str, Any] # Captures the mood state associated with the imprint
    topics: List[str] # List of keywords or topics associated with the imprint
    timestamp: str # ISO 8601 format timestamp
