"""
Exposes the Pathos Subconscious Node functionalities via a FastAPI application.

This API allows external systems to:
- Inject conversation and action context into the node.
- Observe the current thoughts, mood, and a summary of recent activity.
- (Placeholder) Receive impulses and memory imprints detected by the node.

The API relies on other modules within the `subconscious_node` package for
core logic such as context management, mood tracking, thought generation (via thinker),
and utility functions.
"""
import logging # Added for explicit logging configuration
from fastapi import FastAPI
import uvicorn # For running the app with Uvicorn
from pydantic import BaseModel
from typing import List, Dict

# Assuming context_store.py, mood.py, utils.py, thinker.py are in the same package/directory
# Also, ensure logger is initialized for this module
logger = logging.getLogger(__name__)
if not logger.handlers: # Ensure basicConfig is called if no handlers are set up
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

from . import context_store
from . import mood
from . import utils
from . import thinker # To access monologue_buffer

# --- FastAPI App Instance ---
app = FastAPI(
    title="Pathos Subconscious Node API",
    description="API for interacting with the Pathos Subconscious Node, injecting context, and observing thoughts.",
    version="0.1.0"
)

# --- Pydantic Models for Request/Response Bodies ---
class ContextInject(BaseModel):
    content: str

class ImpulsePayload(BaseModel):
    thought: str
    mood_snapshot: Dict
    timestamp: str

class MemoryImprintPayload(BaseModel):
    content: str
    mood: Dict
    topics: List[str]
    timestamp: str

class NodeControlCommand(BaseModel):
    node_state: str
    daily_summary: str | None = None

class MoodUpdatePayload(BaseModel):
    mood_aspects: Dict[str, float]

class CurrentThoughtsResponse(BaseModel):
    recent_thoughts: List[str]
    mood: Dict
    summary: str

class MessageResponse(BaseModel):
    message: str
    context: str | None = None
    data: Dict | None = None


# --- API Endpoints ---

@app.post("/inject/conversation", response_model=MessageResponse, tags=["Context Injection"])
async def inject_conversation(data: ContextInject):
    """
    Injects a piece of conversation context into the subconscious node.
    This context will be used in subsequent thought generation prompts.
    """
    context_store.add_conversation_context(data.content)
    return {"message": "Conversation context injected", "context": data.content}

@app.post("/inject/action", response_model=MessageResponse, tags=["Context Injection"])
async def inject_action(data: ContextInject):
    """
    Injects an action context (e.g., user performed an action) into the subconscious node.
    This context will be used in subsequent thought generation prompts.
    """
    context_store.add_action_context(data.content)
    return {"message": "Action context injected", "context": data.content}

@app.get("/current_thoughts", response_model=CurrentThoughtsResponse, tags=["Observation"])
async def get_thoughts():
    """
    Retrieves the most recent thoughts from the monologue buffer,
    the current mood, and a summary of recent thoughts.
    """
    # Access monologue_buffer safely, ensuring we don't go out of bounds
    buffer_len = len(thinker.monologue_buffer)
    num_thoughts_to_fetch = min(buffer_len, 5)
    recent_thoughts = thinker.monologue_buffer[-num_thoughts_to_fetch:]

    current_mood_snapshot = mood.get_current_mood()
    # The summarize_thoughts function is a placeholder, so its output will be fixed
    summary = utils.summarize_thoughts(recent_thoughts)

    return {
        "recent_thoughts": recent_thoughts,
        "mood": current_mood_snapshot,
        "summary": summary
    }

@app.post("/v1/pathos/impulse", response_model=MessageResponse, tags=["External Integration (Placeholder)"])
async def receive_impulse(payload: ImpulsePayload):
    """
    Placeholder endpoint for receiving impulses detected by the subconscious node.
    In a real system, this might trigger external actions or logging.
    """
    print(f"Subconscious node API received impulse: {payload.dict()}")
    return {"message": "Impulse received by subconscious node (placeholder)", "data": payload.dict()}

@app.post("/v1/pathos/memory/imprint", response_model=MessageResponse, tags=["External Integration (Placeholder)"])
async def receive_memory_imprint(payload: MemoryImprintPayload):
    """
    Placeholder endpoint for receiving memory imprints generated by the subconscious node.
    In a real system, this would integrate with a long-term memory storage.
    """
    print(f"Subconscious node API received memory imprint: {payload.dict()}")
    return {"message": "Memory imprint received by subconscious node (placeholder)", "data": payload.dict()}

@app.get("/", include_in_schema=False)
async def root():
    return {"message": "Pathos Subconscious Node is active. See /docs for API details."}

@app.post("/control/state", response_model=MessageResponse, tags=["Node Control"])
async def control_node_state(command: NodeControlCommand):
    """
    Updates the node's operational state (e.g., AWAKE_THINKING, SLEEPING_DREAMING)
    and can provide a daily summary for dream generation.
    It also starts or stops the monologue loop based on the target state.
    """
    previous_state = thinker.current_node_state
    new_state = command.node_state
    action_taken = "none"

    thinker.current_node_state = new_state # Update state first

    if command.daily_summary is not None:
        thinker.current_daily_summary_for_dreaming = command.daily_summary
        summary_status = "updated"
    else:
        summary_status = "not provided (or not applicable)"

    # Logic for starting/stopping the thread based on the new state
    if new_state == thinker.NODE_STATE_AWAKE_THINKING or new_state == thinker.NODE_STATE_SLEEPING_DREAMING:
        if previous_state == thinker.NODE_STATE_IDLE or previous_state not in [thinker.NODE_STATE_AWAKE_THINKING, thinker.NODE_STATE_SLEEPING_DREAMING]:
            thinker.start_monologue_loop_thread()
            action_taken = "monologue_loop_started"
        else:
            action_taken = "monologue_loop_state_changed_but_already_running"
        logger.info(f"Node state set to '{new_state}'. Monologue loop should be running/starting.")
    elif new_state == thinker.NODE_STATE_IDLE:
        thinker.stop_monologue_loop_thread()
        action_taken = "monologue_loop_stopped"
        logger.info(f"Node state set to '{new_state}'. Monologue loop stopped.")
    else: # Unknown state
        thinker.stop_monologue_loop_thread() # Stop if unknown state is commanded
        action_taken = f"monologue_loop_stopped_due_to_unknown_state ({new_state})"
        logger.warning(f"Node commanded to unknown state '{new_state}'. Monologue loop stopped as a precaution.")


    return {
        "message": f"Node state changed from '{previous_state}' to '{new_state}'. Daily summary {summary_status}. Action: {action_taken}.",
        "data": {
            "new_state": new_state,
            "previous_state": previous_state,
            "daily_summary_provided": command.daily_summary is not None,
            "loop_action": action_taken
        }
    }

@app.post("/control/mood", response_model=MessageResponse, tags=["Node Control"])
async def control_node_mood(payload: MoodUpdatePayload):
    """
    Updates the subconscious node's internal mood state.
    """
    try:
        mood.update_mood(payload.mood_aspects)
        logger.info(f"Subconscious node mood updated with aspects: {payload.mood_aspects}")
        return {
            "message": "Node mood updated successfully.",
            "data": {"updated_aspects": payload.mood_aspects}
        }
    except Exception as e:
        logger.exception(f"Error updating subconscious node mood: {e}")
        # Consider raising HTTPException for client feedback
        return {
            "message": f"Failed to update node mood: {str(e)}",
            "data": {"received_aspects": payload.mood_aspects}
        }

# --- FastAPI Application Lifecycle Events ---
@app.on_event("startup")
async def startup_event():
    logger.info("Subconscious Node API starting up. Monologue loop will await control command to start.")
    # The monologue loop is NOT auto-started here anymore.
    # It's started by a /control/state command setting state to AWAKE_THINKING or SLEEPING_DREAMING.
    # Ensure initial state in thinker.py is IDLE or similar non-processing state.
    thinker.current_node_state = thinker.NODE_STATE_IDLE # Explicitly set to IDLE on startup

@app.on_event("shutdown")
async def shutdown_event():
    logger.info("Subconscious Node API shutting down. Stopping monologue loop.")
    thinker.stop_monologue_loop_thread()

# --- Main Block to Run the App ---
if __name__ == '__main__':
    print("Starting Pathos Subconscious Node API server...")
    # Note: The monologue_loop in thinker.py is now managed by API calls and
    # FastAPI lifecycle events (startup/shutdown).
    # If running this __main__ directly, the loop won't start automatically unless
    # thinker.start_monologue_loop_thread() is explicitly called here for testing,
    # or a /control/state API call is made after startup.
    uvicorn.run(app, host="0.0.0.0", port=8000)
