"""
Handles detection of impulses and imprints from thoughts.

This module analyzes thoughts generated by the Pathos Subconscious Node
to identify significant patterns:
- Impulses: Thoughts that suggest a desire for immediate action,
  influenced by the current mood's impulsiveness. These are POSTed to Eidos.
- Imprints: Thoughts that represent realizations, new understandings, or
  significant memories. These are stored locally in `soft_memory.jsonl`
  and also POSTed to Eidos.
"""
import json
import os
import datetime
import logging # Added logging
import requests # Added requests
import mood  # Import local modules using absolute imports

# --- Constants and Configuration ---
IMPULSE_KEYWORDS = ["i want", "maybe i should", "i should call", "i need to"]

# Core realization and understanding keywords that indicate potential significance
IMPRINT_KEYWORDS = [
    "realize", "understand", "figured out",
    "discovered", "finally see", "makes sense now",
    "never knew", "now I get",
    "changed my perspective", "hit me"
]

# Words that signal genuine emotional or personal significance
SIGNIFICANCE_BOOSTERS = [
    "always felt", "never understood until now", 
    "changed how I", "life-changing",
    "deeply", "profound", "breakthrough",
    "finally understand why I",
    "explains so much about",
    "connection between",
    "pattern in my",
    "root cause",
    "deeper meaning",
    "true reason"
]

# Phrases that suggest mundane or routine thoughts (used to filter out non-significant content)
MUNDANE_FILTERS = [
    "should eat", "need to buy", "forgot to", "left the",
    "wonder if", "maybe later", "probably should",
    "might be", "could try", "remember to",
    "feels like", "looks like", "sounds like",
    "kind of", "sort of", "bit like"
]

# Determine the absolute path to config.json relative to this file's directory
# This ensures that the path is correct regardless of where the script is run from.
# os.path.dirname(__file__) gives the directory where this detectors.py file is located.
# os.path.abspath(...) ensures it's an absolute path.
MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE_PATH = os.path.join(MODULE_DIR, 'config.json')
SOFT_MEMORY_FILE_PATH = os.path.join(MODULE_DIR, 'soft_memory.jsonl')


# --- Logging Setup ---
logger = logging.getLogger(__name__)
# Configure basic logging if not already configured (e.g. by thinker.py)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')


# --- Load Configuration ---
impulse_threshold = 0.7 # Default value
EIDOS_API_BASE_URL = "http://localhost:8080" # Default Eidos API URL

if os.path.exists(CONFIG_FILE_PATH):
    try:
        with open(CONFIG_FILE_PATH, 'r') as f:
            config_data = json.load(f)
        impulse_threshold = config_data.get("mood_settings", {}).get("impulse_threshold", impulse_threshold)
        EIDOS_API_BASE_URL = config_data.get("eidos_api_base_url", EIDOS_API_BASE_URL)

        if EIDOS_API_BASE_URL == "http://localhost:8080" and "eidos_api_base_url" not in config_data:
            logger.warning(f"EIDOS_API_BASE_URL not found in {CONFIG_FILE_PATH}, using default: {EIDOS_API_BASE_URL}")
        if impulse_threshold == 0.7 and "impulse_threshold" not in config_data.get("mood_settings", {}):
             logger.info(f"impulse_threshold not found in {CONFIG_FILE_PATH} under mood_settings, using default: {impulse_threshold}")

    except json.JSONDecodeError as e:
        logger.error(f"Error decoding JSON from {CONFIG_FILE_PATH}: {e}. Using default impulse_threshold: {impulse_threshold} and EIDOS_API_BASE_URL: {EIDOS_API_BASE_URL}")
    except Exception as e:
        logger.error(f"Unexpected error loading config from {CONFIG_FILE_PATH}: {e}. Using defaults.")
else:
    logger.warning(f"{CONFIG_FILE_PATH} not found. Using default impulse_threshold: {impulse_threshold} and EIDOS_API_BASE_URL: {EIDOS_API_BASE_URL}")


# --- Detector Functions ---

def calculate_thought_significance(thought: str) -> float:
    """
    Calculate a significance score for a thought based on various criteria.
    Returns a float between 0 and 1.
    """
    thought_lower = thought.lower()
    score = 0.0
    
    # Check for explicit memory imprint tags first
    if "<remember>" in thought and "</remember>" in thought:
        score += 0.6

    # Check for significant insight indicators
    for keyword in IMPRINT_KEYWORDS:
        if keyword in thought_lower:
            score += 0.3
            break

    # Add score for each significance booster found
    booster_count = 0
    for booster in SIGNIFICANCE_BOOSTERS:
        if booster in thought_lower:
            score += 0.2
            booster_count += 1
            if booster_count >= 2:  # Cap the boost after 2 boosters
                break

    # Reduce score if mundane filters are present
    mundane_count = 0
    for filter_phrase in MUNDANE_FILTERS:
        if filter_phrase in thought_lower:
            score -= 0.15
            mundane_count += 1
            if mundane_count >= 2:  # Cap the reduction after 2 mundane phrases
                break

    # Check thought complexity and depth
    sentences = thought.split('.')
    if len(sentences) >= 3:  # Reward more complex, multi-part thoughts
        score += 0.1
    
    # Normalize score to 0-1 range
    return min(max(score, 0.0), 1.0)

def extract_relevant_impulse(thought: str) -> str:
    """
    Extracts the actionable part of an impulse thought.
    Returns the sentence or clause containing the impulse trigger.
    """
    thought_lower = thought.lower()
    sentences = thought.replace("...", ".").split(".")
    
    for keyword in IMPULSE_KEYWORDS:
        if keyword in thought_lower:
            # Find the sentence containing the impulse
            for sentence in sentences:
                if keyword in sentence.lower():
                    return sentence.strip()
    
    return thought

def check_for_impulse(thought: str, current_mood_snapshot: dict) -> dict | None:
    """
    Checks if a thought qualifies as an impulse and POSTs it to Eidos API.
    Only sends the relevant actionable part of the thought.
    """
    thought_lower = thought.lower()
    for keyword in IMPULSE_KEYWORDS:
        if keyword in thought_lower:
            if current_mood_snapshot.get("impulsiveness", 0) > impulse_threshold:
                # Extract the relevant part containing the impulse
                relevant_thought = extract_relevant_impulse(thought)
                
                impulse_data_dict = {
                    "thought": relevant_thought,
                    "original_thought": thought,  # Keep the original for context
                    "mood_snapshot": current_mood_snapshot,
                    "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat()
                }

                target_url = f"{EIDOS_API_BASE_URL}/v1/pathos/impulse"
                logger.info(f"IMPULSE DETECTED: \"{thought[:50]}...\". Attempting to send to Eidos API: {target_url}")
                try:
                    response = requests.post(target_url, json=impulse_data_dict, timeout=10)
                    response.raise_for_status()
                    logger.info(f"Successfully sent impulse to Eidos: \"{impulse_data_dict['thought'][:50]}...\". Response: {response.status_code}")
                except requests.exceptions.RequestException as e:
                    logger.error(f"Failed to send impulse to Eidos API at {target_url}. Error: {e}")

                return impulse_data_dict
            else:
                logger.debug(f"Impulse keyword \"{keyword}\" found in \"{thought}\", but impulsiveness ({current_mood_snapshot.get('impulsiveness', 0)}) not above threshold ({impulse_threshold}).")
    return None

def extract_relevant_thought_segment(thought: str) -> str:
    """
    Extracts the most significant part of a thought, particularly looking for
    content between <remember> tags or sentences containing significant keywords.
    """
    # First check for <remember> tags
    if "<remember>" in thought and "</remember>" in thought:
        start = thought.find("<remember>") + len("<remember>")
        end = thought.find("</remember>")
        return thought[start:end].strip()
    
    # Split into sentences, handling ellipsis
    sentences = [s.strip() for s in thought.replace("...", ".").split(".") if s.strip()]
    
    max_score = 0
    most_relevant_sentence = ""
    
    for sentence in sentences:
        sentence_lower = sentence.lower()
        score = 0
        
        # Check for insight keywords
        if any(keyword in sentence_lower for keyword in IMPRINT_KEYWORDS):
            score += 0.5
        
        # Check for significance boosters
        for booster in SIGNIFICANCE_BOOSTERS:
            if booster in sentence_lower:
                score += 0.3
        
        # Reduce score for mundane content
        for filter_phrase in MUNDANE_FILTERS:
            if filter_phrase in sentence_lower:
                score -= 0.2
        
        if score > max_score:
            max_score = score
            most_relevant_sentence = sentence

    # Return the most significant sentence, or the original thought if no sentence was significant enough
    return thought

def check_for_imprint(thought: str, current_mood_snapshot: dict) -> dict | None:
    """
    Checks if a thought qualifies as an imprint using stricter criteria.
    A thought must have sufficient significance and contextual relevance
    to be remembered. Only stores and sends the most relevant part of the thought.
    """
    significance = calculate_thought_significance(thought)
    significance_threshold = 0.6  # Increased threshold for memory imprint
    
    if significance >= significance_threshold:
        # Extract the most relevant part of the thought
        relevant_content = extract_relevant_thought_segment(thought)
        
        # Additional validation - check if the extracted content is too mundane
        if any(filter_phrase in relevant_content.lower() for filter_phrase in MUNDANE_FILTERS):
            logger.debug(f"Thought passed significance threshold but contains mundane content: \"{relevant_content[:50]}...\"")
            return None
            
        imprint_data_dict = {
            "content": relevant_content,
            "original_thought": thought,
            "mood": current_mood_snapshot,
            "topics": ["placeholder_topic"],
            "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "significance": significance
        }

        logger.info(f"IMPRINT DETECTED: \"{thought[:50]}...\" (significance: {significance:.2f})")

        # 1. Append to local soft_memory.jsonl
        try:
            with open(SOFT_MEMORY_FILE_PATH, 'a') as f:
                f.write(json.dumps(imprint_data_dict) + '\n')
            logger.info(f"Successfully appended imprint to local file: {SOFT_MEMORY_FILE_PATH}")
        except IOError as e:
            logger.error(f"Could not write imprint to {SOFT_MEMORY_FILE_PATH}: {e}")

        # 2. Send to Eidos API
        target_url = f"{EIDOS_API_BASE_URL}/v1/pathos/memory/imprint"
        logger.info(f"Attempting to send memory imprint to Eidos API: {target_url}")
        try:
            response = requests.post(target_url, json=imprint_data_dict, timeout=10)
            response.raise_for_status()
            logger.info(f"Successfully sent memory imprint to Eidos: \"{imprint_data_dict['content'][:50]}...\". Response: {response.status_code}")
        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to send memory imprint to Eidos API at {target_url}. Error: {e}")

        return imprint_data_dict
    else:
        logger.debug(f"Thought not significant enough for imprint (score: {significance:.2f}): \"{thought[:50]}...\"")
    return None

if __name__ == '__main__':
    # Setup basic logging for testing this module directly
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    logger.info(f"Detectors initialized for testing. Impulse threshold: {impulse_threshold}. Eidos API Base: {EIDOS_API_BASE_URL}")
    logger.info("NOTE: For these tests to fully succeed in sending data, the Eidos API server must be running and accessible.")

    # Test mood setup
    # from .mood import update_mood # Not needed if get_current_mood() is not used directly in tests
    # Instead, we pass mood snapshots directly.

    test_mood_high_impulsiveness = {"impulsiveness": 0.85, "laziness": 0.3, "name": "Excited"}
    test_mood_low_impulsiveness = {"impulsiveness": 0.1, "laziness": 0.7, "name": "Calm"}

    # Test Impulse Detection
    print("\n--- Testing Impulse Detection ---")
    thought1 = "I want to tell everyone about this amazing new song I heard!"
    impulse1 = check_for_impulse(thought1, test_mood_high_impulsiveness)
    assert impulse1 is not None
    assert impulse1["thought"] == thought1

    thought2 = "Maybe I should just stay quiet and observe for now."
    impulse2 = check_for_impulse(thought2, test_mood_low_impulsiveness)
    assert impulse2 is None # Should not trigger due to low impulsiveness

    thought3 = "This is an interesting observation about cloud patterns." # No impulse keyword
    impulse3 = check_for_impulse(thought3, test_mood_high_impulsiveness)
    assert impulse3 is None

    thought4 = "I need to get some coffee to focus."
    impulse4 = check_for_impulse(thought4, test_mood_high_impulsiveness)
    assert impulse4 is not None
    assert impulse4["thought"] == thought4

    # Test Imprint Detection
    print("\n--- Testing Imprint Detection ---")
    # Clean up soft_memory.jsonl for this test run
    if os.path.exists(SOFT_MEMORY_FILE_PATH):
        os.remove(SOFT_MEMORY_FILE_PATH)
        logger.info(f"Removed existing test soft_memory file: {SOFT_MEMORY_FILE_PATH}")

    thought_imprint1 = "I finally realize how important consistent daily habits are for long-term goals."
    imprint1 = check_for_imprint(thought_imprint1, test_mood_low_impulsiveness)
    assert imprint1 is not None
    assert imprint1["content"] == thought_imprint1

    thought_imprint2 = "I remember that day clearly, the air was crisp and the sky was a brilliant blue."
    imprint2 = check_for_imprint(thought_imprint2, test_mood_high_impulsiveness)
    assert imprint2 is not None
    assert imprint2["content"] == thought_imprint2

    thought_no_imprint = "Just a regular thought, nothing particularly insightful."
    imprint3 = check_for_imprint(thought_no_imprint, test_mood_low_impulsiveness)
    assert imprint3 is None

    print("\n--- Verifying soft_memory.jsonl (after test imprints) ---")
    if os.path.exists(SOFT_MEMORY_FILE_PATH):
        with open(SOFT_MEMORY_FILE_PATH, 'r') as f:
            lines = f.readlines()
            print(f"Found {len(lines)} lines in {SOFT_MEMORY_FILE_PATH}.")
            if lines:
                print("Last line:", lines[-1].strip())
                try:
                    json.loads(lines[-1].strip())
                    print("Last line is valid JSON.")
                except json.JSONDecodeError:
                    print("Error: Last line is NOT valid JSON.")
            assert len(lines) == 2 # Based on the two successful imprints above
    else:
        print(f"{SOFT_MEMORY_FILE_PATH} not found, but was expected to be created.")

    print("\nDetector tests finished. Check logs for HTTP request success/failure to Eidos.")
