"""
Handles detection of impulses and imprints from thoughts.

This module analyzes thoughts generated by the Pathos Subconscious Node
to identify significant patterns:
- Impulses: Thoughts that suggest a desire for immediate action,
  influenced by the current mood's impulsiveness. These are POSTed to Eidos.
- Imprints: Thoughts that represent realizations, new understandings, or
  significant memories. These are stored locally in `soft_memory.jsonl`
  and also POSTed to Eidos.
"""
import json
import os
import datetime
import logging # Added logging
import requests # Added requests

# Assuming mood.py is in the same directory (or package)
from .mood import get_current_mood

# --- Constants and Configuration ---
IMPULSE_KEYWORDS = [
    "i want", "maybe i should", "i should call", "i need to",
    "tell someone", "ask about", "should share",
    "let's try", "time to", "got to get that done",
    "must", "really need to"
]
IMPRINT_KEYWORDS = [
    "realize", "understand", "remember", "come to terms with", "finally grasp",
    "feel like", "starting to feel", "sense that", # Note: 'feel like' could be broad, monitor impact
    "it all connects", "makes sense now", "so that's why",
    "decided that", "concluded", "my take is"
]

# Determine the absolute path to config.json relative to this file's directory
# This ensures that the path is correct regardless of where the script is run from.
# os.path.dirname(__file__) gives the directory where this detectors.py file is located.
# os.path.abspath(...) ensures it's an absolute path.
MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE_PATH = os.path.join(MODULE_DIR, 'config.json')
SOFT_MEMORY_FILE_PATH = os.path.join(MODULE_DIR, 'soft_memory.jsonl')


# --- Logging Setup ---
logger = logging.getLogger(__name__)
# Configure basic logging if not already configured (e.g. by thinker.py)
if not logger.handlers:
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')


# --- Configuration Loading (Mirrors logic from utils.py for relevant parts) ---
DEFAULT_MOOD_IMPULSE_THRESHOLD = 0.7
DEFAULT_EIDOS_API_BASE_URL = "http://localhost:8080" # Default Eidos API URL

impulse_threshold = DEFAULT_MOOD_IMPULSE_THRESHOLD
EIDOS_API_BASE_URL = DEFAULT_EIDOS_API_BASE_URL

config_data_detectors = {}
if os.path.exists(CONFIG_FILE_PATH):
    try:
        with open(CONFIG_FILE_PATH, 'r') as f:
            config_data_detectors = json.load(f)
        logger.info(f"Detectors: Successfully loaded configuration from {CONFIG_FILE_PATH}")
    except Exception as e:
        logger.error(f"Detectors: Error loading config from {CONFIG_FILE_PATH}: {e}. Using defaults or env vars.", exc_info=True)
else:
    logger.info(f"Detectors: Config file {CONFIG_FILE_PATH} not found. Using defaults or env vars.")

# Mood Settings
_mood_settings_json = config_data_detectors.get("mood_settings", {})
_json_impulse_threshold = _mood_settings_json.get("impulse_threshold", DEFAULT_MOOD_IMPULSE_THRESHOLD)
impulse_threshold = float(os.getenv("SUBPROCESS_MOOD_IMPULSE_THRESHOLD", _json_impulse_threshold))

# Eidos API Base URL
_json_eidos_api_url = config_data_detectors.get("eidos_api_base_url", DEFAULT_EIDOS_API_BASE_URL)
EIDOS_API_BASE_URL = os.getenv("SUBPROCESS_EIDOS_API_BASE_URL", _json_eidos_api_url)

logger.info(f"Detectors Effective impulse_threshold: {impulse_threshold} (Env > JSON > Default)")
logger.info(f"Detectors Effective EIDOS_API_BASE_URL: '{EIDOS_API_BASE_URL}' (Env > JSON > Default)")


# --- Detector Functions ---

def check_for_impulse(thought: str, current_mood_snapshot: dict) -> dict | None:
    """
    Checks if a thought qualifies as an impulse and POSTs it to Eidos API.
    """
    thought_lower = thought.lower()
    for keyword in IMPULSE_KEYWORDS:
        if keyword in thought_lower:
            if current_mood_snapshot.get("impulsiveness", 0) > impulse_threshold:
                impulse_data_dict = { # Renamed for clarity
                    "thought": thought,
                    "mood_snapshot": current_mood_snapshot,
                    "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat()
                }

                target_url = f"{EIDOS_API_BASE_URL}/v1/pathos/impulse"
                logger.info(f"IMPULSE DETECTED: \"{thought[:50]}...\". Attempting to send to Eidos API: {target_url}")
                try:
                    response = requests.post(target_url, json=impulse_data_dict, timeout=10)
                    response.raise_for_status()
                    logger.info(f"Successfully sent impulse to Eidos: \"{impulse_data_dict['thought'][:50]}...\". Response: {response.status_code}")
                except requests.exceptions.RequestException as e:
                    logger.error(f"Failed to send impulse to Eidos API at {target_url}. Error: {e}")

                return impulse_data_dict
            else:
                logger.debug(f"Impulse keyword \"{keyword}\" found in \"{thought}\", but impulsiveness ({current_mood_snapshot.get('impulsiveness', 0)}) not above threshold ({impulse_threshold}).")
    return None

def check_for_imprint(thought: str, current_mood_snapshot: dict) -> dict | None:
    """
    Checks if a thought qualifies as an imprint, appends to local `soft_memory.jsonl`,
    and POSTs it to Eidos API.
    """
    thought_lower = thought.lower()
    for keyword in IMPRINT_KEYWORDS:
        if keyword in thought_lower:
            imprint_data_dict = { # Renamed for clarity
                "content": thought, # Field name matches Eidos ImprintData model
                "mood": current_mood_snapshot,
                "topics": ["placeholder_topic"],
                "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat()
            }

            logger.info(f"IMPRINT DETECTED: \"{thought[:50]}...\".")

            # 1. Append to local soft_memory.jsonl
            try:
                with open(SOFT_MEMORY_FILE_PATH, 'a') as f:
                    f.write(json.dumps(imprint_data_dict) + '\n')
                logger.info(f"Successfully appended imprint to local file: {SOFT_MEMORY_FILE_PATH}")
            except IOError as e:
                logger.error(f"Could not write imprint to {SOFT_MEMORY_FILE_PATH}: {e}")

            # 2. Send to Eidos API
            target_url = f"{EIDOS_API_BASE_URL}/v1/pathos/memory/imprint"
            logger.info(f"Attempting to send memory imprint to Eidos API: {target_url}")
            try:
                response = requests.post(target_url, json=imprint_data_dict, timeout=10)
                response.raise_for_status()
                logger.info(f"Successfully sent memory imprint to Eidos: \"{imprint_data_dict['content'][:50]}...\". Response: {response.status_code}")
            except requests.exceptions.RequestException as e:
                logger.error(f"Failed to send memory imprint to Eidos API at {target_url}. Error: {e}")

            return imprint_data_dict
    return None

if __name__ == '__main__':
    # Setup basic logging for testing this module directly
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    logger.info(f"Detectors initialized for testing. Impulse threshold: {impulse_threshold}. Eidos API Base: {EIDOS_API_BASE_URL}")
    logger.info("NOTE: For these tests to fully succeed in sending data, the Eidos API server must be running and accessible.")

    # Test mood setup
    # from .mood import update_mood # Not needed if get_current_mood() is not used directly in tests
    # Instead, we pass mood snapshots directly.

    test_mood_high_impulsiveness = {"impulsiveness": 0.85, "laziness": 0.3, "name": "Excited"}
    test_mood_low_impulsiveness = {"impulsiveness": 0.1, "laziness": 0.7, "name": "Calm"}

    # Test Impulse Detection
    print("\n--- Testing Impulse Detection ---")
    thought1 = "I want to tell everyone about this amazing new song I heard!"
    impulse1 = check_for_impulse(thought1, test_mood_high_impulsiveness)
    assert impulse1 is not None
    assert impulse1["thought"] == thought1

    thought2 = "Maybe I should just stay quiet and observe for now."
    impulse2 = check_for_impulse(thought2, test_mood_low_impulsiveness)
    assert impulse2 is None # Should not trigger due to low impulsiveness

    thought3 = "This is an interesting observation about cloud patterns." # No impulse keyword
    impulse3 = check_for_impulse(thought3, test_mood_high_impulsiveness)
    assert impulse3 is None

    thought4 = "I need to get some coffee to focus."
    impulse4 = check_for_impulse(thought4, test_mood_high_impulsiveness)
    assert impulse4 is not None
    assert impulse4["thought"] == thought4

    # Test Imprint Detection
    print("\n--- Testing Imprint Detection ---")
    # Clean up soft_memory.jsonl for this test run
    if os.path.exists(SOFT_MEMORY_FILE_PATH):
        os.remove(SOFT_MEMORY_FILE_PATH)
        logger.info(f"Removed existing test soft_memory file: {SOFT_MEMORY_FILE_PATH}")

    thought_imprint1 = "I finally realize how important consistent daily habits are for long-term goals."
    imprint1 = check_for_imprint(thought_imprint1, test_mood_low_impulsiveness)
    assert imprint1 is not None
    assert imprint1["content"] == thought_imprint1

    thought_imprint2 = "I remember that day clearly, the air was crisp and the sky was a brilliant blue."
    imprint2 = check_for_imprint(thought_imprint2, test_mood_high_impulsiveness)
    assert imprint2 is not None
    assert imprint2["content"] == thought_imprint2

    thought_no_imprint = "Just a regular thought, nothing particularly insightful."
    imprint3 = check_for_imprint(thought_no_imprint, test_mood_low_impulsiveness)
    assert imprint3 is None

    print("\n--- Verifying soft_memory.jsonl (after test imprints) ---")
    if os.path.exists(SOFT_MEMORY_FILE_PATH):
        with open(SOFT_MEMORY_FILE_PATH, 'r') as f:
            lines = f.readlines()
            print(f"Found {len(lines)} lines in {SOFT_MEMORY_FILE_PATH}.")
            if lines:
                print("Last line:", lines[-1].strip())
                try:
                    json.loads(lines[-1].strip())
                    print("Last line is valid JSON.")
                except json.JSONDecodeError:
                    print("Error: Last line is NOT valid JSON.")
            assert len(lines) == 2 # Based on the two successful imprints above
    else:
        print(f"{SOFT_MEMORY_FILE_PATH} not found, but was expected to be created.")

    print("\nDetector tests finished. Check logs for HTTP request success/failure to Eidos.")
