"""
Handles detection of impulses and imprints from thoughts.

This module analyzes thoughts generated by the Pathos Subconscious Node
to identify significant patterns:
- Impulses: Thoughts that suggest a desire for immediate action,
  influenced by the current mood's impulsiveness.
- Imprints: Thoughts that represent realizations, new understandings, or
  significant memories, which are then stored in a soft memory log.
"""
import json
import os
import datetime
from .mood import get_current_mood # Assuming mood.py is in the same directory

# --- Constants and Configuration ---
IMPULSE_KEYWORDS = ["i want", "maybe i should", "i should call", "i need to"]
IMPRINT_KEYWORDS = ["realize", "understand", "remember", "come to terms with", "finally grasp"]
CONFIG_FILE_PATH = "subconscious_node/config.json"
SOFT_MEMORY_FILE_PATH = "subconscious_node/soft_memory.jsonl"

# Load impulse_threshold from config
impulse_threshold = 0.7 # Default value
try:
    with open(CONFIG_FILE_PATH, 'r') as f:
        config_data = json.load(f)
        impulse_threshold = config_data.get("mood_settings", {}).get("impulse_threshold", 0.7)
except FileNotFoundError:
    print(f"Warning: Config file {CONFIG_FILE_PATH} not found. Using default impulse_threshold: {impulse_threshold}")
except json.JSONDecodeError:
    print(f"Warning: Could not decode JSON from {CONFIG_FILE_PATH}. Using default impulse_threshold: {impulse_threshold}")
except Exception as e:
    print(f"Warning: An unexpected error occurred while reading config: {e}. Using default impulse_threshold: {impulse_threshold}")


# --- Detector Functions ---

def check_for_impulse(thought: str, current_mood_snapshot: dict) -> dict | None:
    """
    Checks if a thought qualifies as an impulse based on keywords and mood.

    An impulse is detected if the thought contains specific keywords and
    the current mood's 'impulsiveness' exceeds a predefined threshold.

    Args:
        thought: The thought string to analyze.
        current_mood_snapshot: A dictionary representing the mood at the time of the thought.

    Returns:
        A dictionary containing impulse data if an impulse is detected, otherwise None.
        The impulse data includes the original thought, a snapshot of the mood,
        and a UTC timestamp.
    """
    thought_lower = thought.lower()
    for keyword in IMPULSE_KEYWORDS:
        if keyword in thought_lower:
            if current_mood_snapshot.get("impulsiveness", 0) > impulse_threshold:
                impulse_data = {
                    "thought": thought,
                    "mood_snapshot": current_mood_snapshot,
                    "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat()
                }
                print(f"IMPULSE DETECTED: \"{thought}\". Would POST to /v1/pathos/impulse with data: {impulse_data}")
                return impulse_data
            else:
                # Keyword found, but mood doesn't meet threshold
                # print(f"Debug: Impulse keyword \"{keyword}\" found in \"{thought}\", but impulsiveness ({current_mood_snapshot.get('impulsiveness', 0)}) is not above threshold ({impulse_threshold}).")
                pass # Optional: log or debug this case
    return None

def check_for_imprint(thought: str, current_mood_snapshot: dict) -> dict | None:
    """
    Checks if a thought qualifies as an imprint based on keywords.

    An imprint is detected if the thought contains specific keywords
    suggesting realization, understanding, or significant memory.
    If detected, the imprint data is also appended to `soft_memory.jsonl`.

    Args:
        thought: The thought string to analyze.
        current_mood_snapshot: A dictionary representing the mood at the time of the thought.

    Returns:
        A dictionary containing imprint data if an imprint is detected, otherwise None.
        The imprint data includes the content of the thought, the mood snapshot,
        placeholder topics, and a UTC timestamp.
    """
    thought_lower = thought.lower()
    for keyword in IMPRINT_KEYWORDS:
        if keyword in thought_lower:
            imprint_data = {
                "content": thought,
                "mood": current_mood_snapshot, # Using the full mood snapshot
                "topics": ["placeholder_topic"], # Placeholder for future topic modeling
                "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat()
            }
            print(f"IMPRINT DETECTED: \"{thought}\". Appending to {SOFT_MEMORY_FILE_PATH} with data: {imprint_data}")

            try:
                with open(SOFT_MEMORY_FILE_PATH, 'a') as f:
                    f.write(json.dumps(imprint_data) + '\n')
            except IOError as e:
                print(f"Error: Could not write to {SOFT_MEMORY_FILE_PATH}: {e}")
                # Depending on desired behavior, could return None here or raise exception
            return imprint_data
    return None

if __name__ == '__main__':
    # Example Usage (for testing purposes)
    print(f"Detectors initialized. Impulse threshold: {impulse_threshold}")

    # Test mood setup
    from .mood import update_mood # Import for testing
    test_mood_high_impulsiveness = {"impulsiveness": 0.8, "laziness": 0.3, "name": "Excited"}
    test_mood_low_impulsiveness = {"impulsiveness": 0.2, "laziness": 0.7, "name": "Calm"}

    # Test Impulse Detection
    print("\n--- Testing Impulse Detection ---")
    thought1 = "I want to tell everyone about this!"
    impulse1 = check_for_impulse(thought1, test_mood_high_impulsiveness)
    assert impulse1 is not None
    assert impulse1["thought"] == thought1

    thought2 = "Maybe I should just stay quiet."
    impulse2 = check_for_impulse(thought2, test_mood_low_impulsiveness) # Should not trigger due to low impulsiveness
    assert impulse2 is None

    thought3 = "This is an interesting observation." # No impulse keyword
    impulse3 = check_for_impulse(thought3, test_mood_high_impulsiveness)
    assert impulse3 is None

    thought4 = "I need to get some coffee."
    impulse4 = check_for_impulse(thought4, test_mood_high_impulsiveness)
    assert impulse4 is not None
    assert impulse4["thought"] == thought4
    
    # Test Imprint Detection
    print("\n--- Testing Imprint Detection ---")
    thought_imprint1 = "I finally realize how important this is."
    imprint1 = check_for_imprint(thought_imprint1, test_mood_low_impulsiveness)
    assert imprint1 is not None
    assert imprint1["content"] == thought_imprint1

    thought_imprint2 = "I remember that day clearly."
    imprint2 = check_for_imprint(thought_imprint2, test_mood_high_impulsiveness)
    assert imprint2 is not None
    assert imprint2["content"] == thought_imprint2

    thought_no_imprint = "Just a regular thought, nothing special."
    imprint3 = check_for_imprint(thought_no_imprint, test_mood_low_impulsiveness)
    assert imprint3 is None

    print("\n--- Verifying soft_memory.jsonl ---")
    if os.path.exists(SOFT_MEMORY_FILE_PATH):
        with open(SOFT_MEMORY_FILE_PATH, 'r') as f:
            lines = f.readlines()
            print(f"Found {len(lines)} lines in {SOFT_MEMORY_FILE_PATH}.")
            if lines:
                print("Last line:", lines[-1].strip())
                # Basic check if the last line is valid JSON
                try:
                    json.loads(lines[-1].strip())
                    print("Last line is valid JSON.")
                except json.JSONDecodeError:
                    print("Error: Last line is NOT valid JSON.")
    else:
        print(f"{SOFT_MEMORY_FILE_PATH} not found (expected if no imprints were made or file was cleared).")

    # Clean up soft_memory.jsonl after test if it was created
    # if os.path.exists(SOFT_MEMORY_FILE_PATH) and (imprint1 or imprint2):
    #     # Potentially delete or clear the file if it's only for testing
    #     # For now, let's leave it to see accumulated results in dev
    #     pass
    print("\nDetector tests finished.")
