from typing import List, Dict, Any

# Definitions for tools related to Pathos's interactions within the simulation,
# especially with NPCs or other Firmament entities.

PATHOS_INTERACTION_TOOLS_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "type": "function",
        "function": {
            "name": "interact_with_npc",
            "description": "Allows Pathos to say something to a specific Non-Player Character (NPC) who is perceived to be present in his current simulated environment. Use this to engage in conversation or direct an action towards an NPC.",
            "parameters": {
                "type": "object",
                "properties": {
                    "npc_id": {
                        "type": "string",
                        "description": "The unique ID of the NPC Pathos wants to talk to or interact with. This ID should be known from the current simulation context (e.g., present NPCs) or prior interactions."
                    },
                    "utterance": {
                        "type": "string",
                        "description": "What Pathos wants to say to the NPC. This can be direct speech or a description of a simple action Pathos is taking towards the NPC."
                    },
                    "conversation_id": {
                        "type": "string",
                        "description": "Optional. The ID of an ongoing conversation. If continuing an existing conversation with this NPC, provide the ID from the previous turn. If starting a new conversation, this can be omitted or a new unique ID can be generated by Pathos."
                    }
                },
                "required": ["npc_id", "utterance"]
            }
        }
    }
    # Future interaction tools could be added here, e.g.:
    # - observe_npc_activity(npc_id: str)
    # - give_item_to_npc(npc_id: str, item_name: str)
]

# It's good practice to have a way to easily access these definitions.
# A function can be helpful if more complex logic is needed later.
def get_pathos_interaction_tool_definitions() -> List[Dict[str, Any]]:
    return PATHOS_INTERACTION_TOOLS_DEFINITIONS
