// webapp/js/dom_elements.js
const $ = id => document.getElementById(id);

export const apiKeyInput = $('api-key-input');
export const apiUrlInput = $('api-url-input');
export const attachedDocumentIndicator = $('attached-document-indicator');
export const attachedDocumentNameSpan = $('attached-document-name'); // Corrected
export const chatContainer = $('chat-container'); // Assumes ID added to HTML
export const chatMessagesArea = $('chat-messages-area');
export const clearBackendMemoryButton = $('clear-backend-memory-button');
export const clearDreamJournalDisplayButton = $('clear-dream-journal-display-button');
export const clearHistoryButton = $('clear-history-button');
export const clearKnowledgeLogDisplayButton = $('clear-knowledge-log-display-button');
export const clearLearningLogDisplayButton = $('clear-learning-log-display-button');
export const clearProactiveButton = $('clear-proactive-button'); // Added
export const clearUserMemoryButton = $('clear-user-memory-button');
export const contextLengthInput = $('context-length-input');
export const dailyBriefingCloseButton = $('daily-briefing-close-button');
export const dailyBriefingContentArea = $('daily-briefing-content-area');
export const dailyBriefingPanel = $('daily-briefing-panel');
export const documentInput = $('document-input');
export const dreamJournalButton = $('dream-journal-button');
export const dreamJournalCloseButton = $('dream-journal-close-button');
export const dreamJournalContentArea = $('dream-journal-content-area');
export const dreamJournalPanel = $('dream-journal-panel');
export const dropdownButton = $('model-dropdown-button'); // Corrected
export const dropdownContent = $('model-dropdown-content'); // Corrected (was already model-dropdown-content)
export const forceWebSearchButton = $('force-web-search-button');
export const getDailyBriefingButton = $('get-daily-briefing-button'); // Added
export const historyButton = $('history-button');
export const historyCloseButton = $('history-close-button');
export const historyContentArea = $('history-content-area');
export const historyPanel = $('history-panel');
export const imageInput = $('image-input');
export const inputContainer = $('input-container'); // Assumes ID added to HTML
export const knowledgeLogButton = $('knowledge-log-button');
export const knowledgeLogCloseButton = $('knowledge-log-close-button');
export const knowledgeLogContentArea = $('knowledge-log-content-area');
export const knowledgeLogPanel = $('knowledge-log-panel');
export const learningLogButton = $('learning-log-button');
export const learningLogCloseButton = $('learning-log-close-button');
export const learningLogContentArea = $('learning-log-content-area');
export const learningLogPanel = $('learning-log-panel');
export const llmProviderUrlInput = $('llm-provider-url-input');
export const microphoneButton = $('microphone-button');
export const modelDisplayName = $('model-display-name');
export const modelDropdownContent = $('model-dropdown-content'); // This was correct
export const modelSelect = $('model-select');
export const modelTemperatureInput = $('model-temperature-input');
export const proactiveButton = $('proactive-button');
export const proactiveCloseButton = $('proactive-close-button');
export const proactiveMessagesArea = $('proactive-messages-area');
export const proactivePanel = $('proactive-panel');
export const proactiveReplyContextDisplay = $('proactive-reply-context-display'); // Assumes ID added to HTML
export const refreshDailyBriefingButton = $('refresh-daily-briefing-button'); // Added
export const refreshDreamJournalButton = $('refresh-dream-journal-button'); // Added
export const refreshKnowledgeLogButton = $('refresh-knowledge-log-button'); // Added
export const refreshLearningLogButton = $('refresh-learning-log-button'); // Added
export const removeAttachedDocumentButton = $('remove-attached-document');
export const resetChatButton = $('reset-chat-button');
export const sendButton = $('send-button');
export const systemPromptButton = $('system-prompt-button');
export const systemPromptClose = $('system-prompt-close');
export const systemPromptInput = $('system-prompt-input');
export const systemPromptPanel = $('system-prompt-panel');
export const systemPromptSave = $('system-prompt-save');
export const uploadDocumentButton = $('upload-document-button');
export const uploadImageButton = $('upload-image-button');
export const userIdInput = $('user-id-input');
export const userInput = $('user-input');
export const weatherCloseButton = $('weather-close'); // Corrected
export const weatherDescriptionDisplay = $('weather-description'); // Corrected
export const weatherHumidityDisplay = $('weather-humidity'); // Corrected
export const weatherLastUpdatedDisplay = $('weather-last-updated'); // Corrected
export const weatherLocationDisplay = $('weather-location'); // Corrected
export const weatherLocationInput = $('weather-location-input');
export const weatherPanel = $('weather-panel');
export const weatherTemperatureDisplay = $('weather-temperature'); // Corrected
export const weatherUpdateButton = $('weather-update-button');
export const weatherWindDisplay = $('weather-wind'); // Corrected
export const ttsToggleButton = $('tts-toggle-button');

console.log('✅ dom_elements.js loaded — all DOM hooks wired (with corrections).');